# Generated by Django 3.0.3 on 2020-02-24 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('nombre_p', models.CharField(max_length=20)),
                ('nombre_m', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('viaje', models.CharField(choices=[('Internacional', 'Internacional'), ('Nacional', 'Nacional')], default='Nacional', max_length=20)),
                ('passport', models.CharField(max_length=16)),
                ('linea_aerea', models.CharField(max_length=30)),
                ('destino', models.CharField(max_length=30)),
                ('fecha_salida', models.DateTimeField()),
                ('fecha_regreso', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
